spark:
  appName: KG Builder

entities:
  - #endpoint: "http://10.132.0.8/bigdata/sparql"
    endpoint: "https://query.wikidata.org/sparql"
    prefixes:
      wd: "http://www.wikidata.org/entity/"
      wdt: "http://www.wikidata.org/prop/direct/"
    queries:
      - q: ?subject wdt:P31 wd:Q4830453 . ?subject ?predicate ?object
        limit: 1500000
      - q: ?root wdt:P31 wd:Q4830453 . ?root ?p_root ?subject . ?subject ?predicate ?object
        limit: 7000000
    partitionSize: 10000

    exclude.predicate.patterns:
      - "wdt-statement"
      - "wdt-reference"

enrichments:
  - endpoint: "http://dbpedia.org/sparql"
    prefixes:
      owl: "http://www.w3.org/2002/07/owl#"
      wd: "http://www.wikidata.org/entity/"
      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    queries:
      - q:
          >
          ?root rdf:type wd:Q43229
          . ?root owl:sameAs ?subject
          . ?root ?predicate ?object
          . FILTER(regex(str(?subject),'^http://www.wikidata'))
        limit: 1700000
      - q:
          >
          ?root1 rdf:type wd:Q43229
          . ?root1 ?p_root ?root
          . ?root owl:sameAs ?subject
          . ?root ?predicate ?object
          . FILTER(regex(str(?subject),'^http://www.wikidata'))
        limit: 5000000
    partitionSize: 10000

store:
  elasticsearch.hadoop:
    es.nodes: elasticsearch
    es.nodes.client.only: true
    es.resource: kg_recognai/resources
    es.mapping.id: id
    #es.batch.flush.manual: 10000
  exclude.features:
    - "http://dbpedia.org/property/establishedDate"
